major refactoring work on our scripts

diff --git a/self-compile b/self-compile
--- a/self-compile
+++ b/self-compile
@@ -1,7 +1,11 @@
 #!/bin/bash
 
-# Exit on error or undefined variable. Good bash hygiene.
 set -eu
+
+if [ ! -d grammars ]; then
+  echo "Couldn't find Silver root. Run as ./self-compile"
+  exit 1
+fi
 
 # Defaults overridable by setting an environment variable:
 SVJVM_FLAGS=${SVJVM_FLAGS:-"-Xmx1800M -Xss6M"}
diff --git a/support/scripts/fetch-jars b/support/scripts/fetch-jars
--- a/support/scripts/fetch-jars
+++ b/support/scripts/fetch-jars
@@ -2,6 +2,13 @@
 
 set -eu
 
+if [ -d ../../grammars ]; then cd ../..; fi
+
+if [ ! -d grammars ]; then
+  echo "Couldn't find Silver root. Run as ./support/scripts/fetch-jars"
+  exit 1
+fi
+
 LOCAL_STORE=/web/research/melt.cs.umn.edu/downloads/silver-dev/jars
 REMOTE_STORE="http://melt.cs.umn.edu/downloads/silver-dev/jars"
 
diff --git a/support/scripts/profile-silver-compiler b/support/scripts/profile-silver-compiler
--- a/support/scripts/profile-silver-compiler
+++ b/support/scripts/profile-silver-compiler
@@ -1,7 +1,11 @@
 #!/bin/bash
 
-if [ ! -d jars ]; then
-  echo "Run from silver root as './support/profile/run.sh'"
+set -eu
+
+if [ -d ../../grammars ]; then cd ../..; fi
+
+if [ ! -d grammars ]; then
+  echo "Couldn't find Silver root. Run as ./support/scripts/profile-silver-compiler"
   exit 1
 fi
 
diff --git a/support/scripts/publish-jars b/support/scripts/publish-jars
--- a/support/scripts/publish-jars
+++ b/support/scripts/publish-jars
@@ -2,6 +2,13 @@
 
 set -eu
 
+if [ -d ../../grammars ]; then cd ../..; fi
+
+if [ ! -d grammars ]; then
+  echo "Couldn't find Silver root. Run as ./support/scripts/publish-jars"
+  exit 2
+fi
+
 DT=$(date +"%Y.%m.%d.%H.%M")
 JARS_STORE=/web/research/melt.cs.umn.edu/downloads/silver-dev/jars
 JARS_BACKUP=/project/melt4/People/ted/jars_bak
@@ -9,11 +16,6 @@ JARS_BACKUP=/project/melt4/People/ted/jars_bak
 if [ ! -d $JARS_STORE ]; then
   echo "Must be running on a umn machine in the melt group."
   exit 1
-fi
-
-if [ ! -d jars ]; then
-  echo "Should be run from root of silver tree."
-  exit 2
 fi
 
 # I like to keep a backup series of our jars...
